access_key = "< AWS access key >"
secret_key = "< AWS secret key >"
region     = "us-east-1"
domain     = "chavo.eu"
api_key    = "< CloudFlare API Key >"
email      = "< You email >"
name       = "vault"
zone_id    = "< CloudFlare Zone ID >"